AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys an ECS cluster to the provided VPC and subnets using an Auto Scaling Group

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String



  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Default: t3.small

  ClusterSize:
    Description: How many ECS hosts do you want to initially deploy?
    Type: Number
    Default: 1

  #VPC:
  #  Description: Choose which VPC this ECS cluster should be deployed to
  #  Type: AWS::EC2::VPC::Id

  Subnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  InstanceSecurityGroup:
    Description: Select the Security Group to use for the ECS cluster hosts
    Type: AWS::EC2::SecurityGroup::Id

  LatestAmiId:
    Description: ECS-Optimized AMI ID
    #Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    #Default: /aws/services/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Type: String
    Default: ami-0150189e4c09ffab5

  InstanceTargetGroupArn:
    Description: LoadBalancer Target Group for instance
    Type: String

  #ContainerTargetGroupArn:
  #  Description: LoadBalancer Target Group for containers
  #  Type: String


Resources:
  ECSLaunchTemplateConfig:
    Type: AWS::EC2::LaunchTemplate
    #DeletionPolicy: Retain
    #UpdateReplacePolicy: Retain
    Properties:
      LaunchTemplateName: !Sub ${EnvironmentName}-launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        # HERE: Prevent public IP assignment and define interface settings
        # CORRECTED: Security Group is only specified HERE inside the interface array
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: false
            Groups:
              - !Ref InstanceSecurityGroup

        IamInstanceProfile:
          Arn: !GetAtt ECSInstanceProfile.Arn
        #SecurityGroupIds:
        #  - !Ref InstanceSecurityGroup
        UserData:
          "Fn::Base64": !Sub |
            #!/bin/bash
            # Use this for your user data (script from top to bottom)
            # install httpd (Linux 2 version)
            yum update -y
            curl -O https://s3.us-west-2.amazonaws.com/amazon-ecs-agent-us-west-2/amazon-ecs-init-latest.x86_64.rpm
            yum localinstall -y amazon-ecs-init-latest.x86_64.rpm
            yum install -y httpd
            yum install -y docker
            systemctl start docker
            systemctl start httpd
            systemctl enable httpd
            systemctl enable docker
            systemctl enable ecs
            echo "ECS_CLUSTER=${ECSCluster}" >> /etc/ecs/ecs.config
            echo "<h1>Hello World from $(hostname -f) </h1>" >> /var/www/html/index.html

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub alb-${EnvironmentName}-asg
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplateConfig
        Version: !GetAtt ECSLaunchTemplateConfig.LatestVersionNumber
      MaxSize: !Ref ClusterSize
      MinSize: !Ref ClusterSize
      DesiredCapacity: !Ref ClusterSize
      VPCZoneIdentifier: !Ref Subnets
      # REQUIRED for Managed Termination Protection on Capacity Providers:
      NewInstancesProtectedFromScaleIn: true
      TargetGroupARNs:
        - !Ref InstanceTargetGroupArn
        # - !Ref ContainerTargetGroupArn
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300


  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-cluster
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  # 2. The ECS Capacity Provider linking the ASG
  EcsCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      Name: !Sub ${EnvironmentName}-capacity-provider
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedTerminationProtection: ENABLED # Requires ASG to have Termination Protection turned on
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 80 # Targets 80% aggregate CPU/Memory utilization across the cluster
          MinimumScalingStepSize: 1
          MaximumScalingStepSize: 2

    # 3. Associating the Capacity Provider with the Cluster
  ClusterCapacityProviderAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      Cluster: !Ref ECSCluster
      CapacityProviders:
        - !Ref EcsCapacityProvider
      DefaultCapacityProviderStrategy:
        - CapacityProvider: !Ref EcsCapacityProvider
          Weight: 1
          Base: 0

  ECSCloudWatchParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ECS
      Name: !Sub "AmazonCloudWatch-${ECSCluster}-ECS"
      Type: String
      Value: !Sub |
        {
          "logs": {
            "force_flush_interval": 5,
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "/var/log/messages",
                    "log_group_name": "${ECSCluster}-/var/log/messages",
                    "log_stream_name": "{instance_id}",
                    "timestamp_format": "%b %d %H:%M:%S"
                  },
                  {
                    "file_path": "/var/log/dmesg",
                    "log_group_name": "${ECSCluster}-/var/log/dmesg",
                    "log_stream_name": "{instance_id}"
                  },
                  {
                    "file_path": "/var/log/docker",
                    "log_group_name": "${ECSCluster}-/var/log/docker",
                    "log_stream_name": "{instance_id}",
                    "timestamp_format": "%Y-%m-%dT%H:%M:%S.%f"
                  },
                  {
                    "file_path": "/var/log/ecs/ecs-init.log",
                    "log_group_name": "${ECSCluster}-/var/log/ecs/ecs-init.log",
                    "log_stream_name": "{instance_id}",
                    "timestamp_format": "%Y-%m-%dT%H:%M:%SZ"
                  },
                  {
                    "file_path": "/var/log/ecs/ecs-agent.log.*",
                    "log_group_name": "${ECSCluster}-/var/log/ecs/ecs-agent.log",
                    "log_stream_name": "{instance_id}",
                    "timestamp_format": "%Y-%m-%dT%H:%M:%SZ"
                  },
                  {
                    "file_path": "/var/log/ecs/audit.log",
                    "log_group_name": "${ECSCluster}-/var/log/ecs/audit.log",
                    "log_stream_name": "{instance_id}",
                    "timestamp_format": "%Y-%m-%dT%H:%M:%SZ"
                  }
                ]
              }
            }
          },
          "metrics": {
            "append_dimensions": {
              "AutoScalingGroupName": "${!aws:AutoScalingGroupName}",
              "InstanceId": "${!aws:InstanceId}",
              "InstanceType": "${!aws:InstanceType}"
            },
            "metrics_collected": {
              "collectd": {
                "metrics_aggregation_interval": 60
              },
              "disk": {
                "measurement": [
                  "used_percent"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                  "/"
                ]
              },
              "mem": {
                "measurement": [
                  "mem_used_percent"
                ],
                "metrics_collection_interval": 60
              },
              "statsd": {
                "metrics_aggregation_interval": 60,
                "metrics_collection_interval": 10,
                "service_address": ":8125"
              }
            }
          }
        }

  # This IAM Role is attached to all of the ECS hosts. It is based on the default role
  # published here:
  # http://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html
  #
  # You can add other IAM policy statements here to allow access from your ECS hosts
  # to other AWS services. Please note that this role will be used by ALL containers
  # running on the ECS host.
  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-ECSRole-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Action:
            - "sts:AssumeRole"
          Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/services-role/AmazonEC2ContainerServiceforEC2Role

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ECSRole

  ECSServiceAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Action:
            - "sts:AssumeRole"
          Effect: Allow
          Principal:
            Service:
              - application-autoscaling.amazonaws.com
      Policies:
        - PolicyName: ecs-services-autoscaling
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - application-autoscaling:*
                - cloudwatch:DescribeAlarms
                - cloudwatch:PutMetricAlarm
                - ecs:DescribeServices
                - ecs:UpdateService
              Resource: "*"

Outputs:
  Cluster:
    Description: A reference to the ECS cluster
    Value: !Ref ECSCluster

  ECSServiceAutoScalingRole:
    Description: A reference to ECS services auto scaling role
    Value: !GetAtt ECSServiceAutoScalingRole.Arn

  ECSAutoScalingGroupName:
    Description: A reference to ECS AutoScaling Group Name
    Value: !Ref ECSAutoScalingGroup