AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys an Application Load Balancer that exposes our various ECS services.
  We create them in a seperate nested template, so it can be referenced by all of the other nested templates.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed to

  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select the Security Group to apply to the Application Load Balancer
    Type: AWS::EC2::SecurityGroup::Id


Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-alb
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup


  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  # Listener Rule to route specific traffic (e.g., /api*) to Port 3000 Target Group
  ApiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - '/api*'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ContainerTargetGroup

  # We define a default target group here, as this is a mandatory Parameters
  # when creating an Application Load Balancer Listener. This is not used, instead
  # a target group is created per-service in each service template (../services/*)
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub tg-${EnvironmentName}-alb-http-80
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /

  ContainerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub tg-${EnvironmentName}-alb-http-3000
      VpcId: !Ref VPC
      Port: 3000
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /


Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref ApplicationLoadBalancer

  #LoadBalancerName:
  #  Description: 'The name of the created Network Load Balancer'
  #  Value: !GetAtt LoadBalancer.LoadBalancerName

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  Listener:
    Description: A reference to a port 80 listener
    Value: !Ref LoadBalancerListener

  InstanceTargetGroupArn:
    Description: A Target group for container instance arn
    Value: !Ref DefaultTargetGroup

  ContainerTargetGroupArn:
    Description: A Target group for container instance arn
    Value: !Ref ContainerTargetGroup

    # Exporting the Port 5000 Target Group ARN so Stack B can find it
  ContainerTargetGroupArnExport:
      Description: 'The ARN of the TCP Port 5000 Target Group exported for other stacks'
      Value: !Ref ContainerTargetGroup
      Export:
        Name: !Sub "${AWS::StackName}-ContainerTargetGroupArn"