AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a VPC, with a pair of public and private subnets spread
  across two Availabilty Zones. It deploys an Internet Gateway, with a default
  route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ),
  and default routes for them in the private subnets.

  It then deploys a highly available ECS cluster using an AutoScaling Group, with
  ECS hosts distributed across multiple Availability Zones.
  
  Finally, it deploys a pair of example ECS services from containers published in
  Amazon EC2 Container Registry (Amazon ECR).

Parameters:
  TemplateUrlBase:
    Type: String
    Default: 'https://cfn-deployment-template.s3.eu-west-2.amazonaws.com/templates'

  Environment:
    Description: List of available environments
    Type: String
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlBase}/stacks/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.0.0.0/20
        PublicSubnet1CIDR: 10.0.0.0/24
        PublicSubnet2CIDR: 10.0.1.0/24
        PrivateSubnet1CIDR: 10.0.8.0/24
        PrivateSubnet2CIDR: 10.0.9.0/24
        DeployToEnvironment: !Ref Environment

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlBase}/stacks/security-groups.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlBase}/stacks/load-balancer.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
        Subnets: !GetAtt VPC.Outputs.PublicSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

Outputs:
  VPC:
    Description: VPC information
    Value: !Ref VPC

  ELB:
    Description: Load Balance Information
    Value: !Ref ALB
