name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Choose deployment environment
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  BUCKET_NAME: cfn-deployment-template

jobs:
  # Local checks
  lock_file:
    name: lock packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: uv lock --locked

  linting:
    runs-on: ubuntu-latest
    needs: [ lock_file ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: lint_cfn
        run: uvx cfn-lint cfn-templates/*.yaml cfn-templates/stacks/*.yaml

      - name: lint_app
        run: uvx ruff check .

  formatting:
    name: format sources
    runs-on: ubuntu-latest
    needs:
      - lock_file
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .

  # create S3 buckets for templates
  create_bucket:
    name: create bucket
    needs:
      - formatting
      - linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy bucket stack
        run: |
          aws cloudformation deploy \
           --stack-name cfn-template-bucket \
           --template-file cfn-templates/bucket.yaml \
           --region $AWS_REGION \
           --capabilities CAPABILITY_NAMED_IAM


  copy_template:
    needs: [ create_bucket ]
    name: upload templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy templates to S3
        run: |
          aws s3 cp cfn-templates/ s3://${BUCKET_NAME}/templates/ --recursive


  validate_templates:
    name: validate templates
    needs:
      - create_bucket
      - copy_template
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate all templates
        run: |
          aws cloudformation validate-template \
           --template-url https://cfn-deployment-template.s3.eu-west-2.amazonaws.com/templates/master.yaml
